<a href="https://colab.research.google.com/github/2003Himansh/numpy1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
python_list=[1,2,3,4,5]
print(python_list)
#1d array
import numpy as np
numpy_array=np.array([1,2,3,4,5])
print(numpy_array)


[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
#2d array or matrix
import numpy as np
ar_2d=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(ar_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# zero value
import numpy as np
zero_array=np.zeros(3)
print(zero_array)
#ones value
ones_array=np.ones((2,3))
print(ones_array)
#full[shape,value]
filled_array=np.full((2,2),7)
print(filled_array)


[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]


In [ ]:
# creating sequencing of number in numpy
import numpy as np
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [ ]:
#create identitiy matrixces
import numpy as np
identitiy_matrix=np.eye(3)
print(identitiy_matrix)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# attribute of numpy
import numpy as np
arr_2d=np.array([[1,2,3],
                [4,5,6]])
print(arr_2d.shape)
print(arr_2d.size)
print(arr_2d.ndim)
print(arr_2d.dtype)
print(arr_2d.itemsize)
print(arr_2d.astype('float'))


(2, 3)
6
2
int64
8
[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
import numpy as np
arr=np.array([10,20,30])
print(arr + 5)



In [ ]:
#operator
import numpy as np
arr=np.array([10,20,30])
print(arr + 5)
print(arr * 2)
print(arr ** 2)


[15 25 35]
[20 40 60]
[100 400 900]


In [ ]:
#aggregation function
import numpy as np
arr=np.array([10,20,30,40,45,65,76,98,46,90,54])
print(np.max(arr))
print(np.min(arr))
print(np.var(arr))
print(np.std(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.sum(arr))
print(np.prod(arr))





98
10
709.9669421487604
26.64520486220289
52.18181818181818
46.0
574
1168882565760000000


In [ ]:
#indexing and slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(arr[3])
print(arr[1:])
print(arr[:-1])
print(arr[2:14:2])
print(arr[::2])
print(arr[::-1])


4
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 3  5  7  9 11 13]
[ 1  3  5  7  9 11 13 15]
[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [ ]:
#fancing indexing
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(arr[[0, 2, 4, 6]])
print(arr[arr>7])


[1 3 5 7]
[ 8  9 10 11 12 13 14 15]


In [ ]:
#reshaping
import numpy as np
arr=np.array([1,2,3,4,5,6])
reshaped_Arr=arr.reshape(2,3)
print(reshaped_Arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr_2d=np.array([[1,2,3], [4,5,6]])
print(arr_2d.ravel())
print(arr_2d.flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
#advanced numpy
#syntax (arr,position,newvalue)
import numpy as np
arr =np.array([1,2,3,4,5,6,7,8,9,10])
print (arr)
new_arr=np.insert(arr,2,100)
print(new_arr)
#2d
arr_2d=np.array([[1,2,3],
                [4,5,6]])
print(arr_2d)
new_arr=np.insert(arr_2d,2, 20,axis=0)#axis=1,None
print(new_arr)
#append used in numpy
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
new_arr=(np.append(arr,[11,12,13,14,15]))
print(new_arr)



[ 1  2  3  4  5  6  7  8  9 10]
[  1   2 100   3   4   5   6   7   8   9  10]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [20 20 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
#concatenate((arr1,arr2,axis=0))
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)


[1 2 3 4 5 6]


In [ ]:
#removing element
import numpy as np
arr=np.array([1,2,4,5,7,6,8])
new_arr=np.delete(arr,4)
print(new_arr)
#delete 2d array
import numpy as np
arr_2d=np.array([[1,2,3],
                [4,5,6]])
new_arr=np.delete(arr_2d,0,axis=0)
print(new_arr)


[1 2 4 5 6 8]
[[4 5 6]]


In [ ]:
#vertically and horizontally stacking
import numpy as np
arr1=np.array([2,4,6])
arr2=np.array([8,9,2])
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))


[[2 4 6]
 [8 9 2]]
[2 4 6 8 9 2]


In [ ]:
#spliting the array
import numpy as np
arr=np.array([10,20,30,40,50,60])
new_arr=np.split(arr,2)
print(new_arr)

[array([10, 20, 30]), array([40, 50, 60])]


In [ ]:
#broadcasting numpy
import numpy as np
prices=np.array([100,200,300])
discount=10
final_price=prices-(prices*discount/100)
print(final_price)


[ 90. 180. 270.]


In [ ]:
import numpy as np
arr=np.array([100,200,300,400,500,600,700,800,900,1000])
result=arr*56564565
print(result)

[ 5656456500 11312913000 16969369500 22625826000 28282282500 33938739000
 39595195500 45251652000 50908108500 56564565000]


In [ ]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6]])
vector=np.array([10,20,30])
result=matrix +vector
print(result)
list1=np.array([1,2,3])
list2=np.array([4,5,6])
result=list1+list2
print(result)

[[11 22 33]
 [14 25 36]]
[5 7 9]


In [ ]:
#handling missing value
import numpy as np
arr=np.array([1,2,np.nan,4,np.nan])
print(np.isnan(arr))
cleaned_arr=np.nan_to_num(arr,nan=0)
print(cleaned_arr)




[False False  True False  True]
[1. 2. 0. 4. 0.]


In [ ]:
import numpy as np
arr=np.array([1,2,np.inf,4,-np.inf,6])
print(np.isinf(arr))
cleaned_arr=np.nan_to_num(arr,posinf=1000,neginf=1000)
print(cleaned_arr)

[False False  True False  True False]
[   1.    2. 1000.    4. 1000.    6.]


In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/sample_data/california_housing_test.csv")
print(df.head())
print ('missing values in each column')
print(df.isnull().sum())
print('Total missing values:')
print(df.isnull().sum())
df['total_bedrooms'].fillna(df['total_bedrooms'].mean(), inplace=True)
df['total_bedrooms'].fillna(df['total_bedrooms'].median(), inplace=True)
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.fillna(df.mean(), inplace=True)
#duplicate
df.drop_duplicates(inplace=True)



   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  
missing values in each column
longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population           

/tmp/ipython-input-576029346.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['total_bedrooms'].fillna(df['total_bedrooms'].mean(), inplace=True)
/tmp/ipython-input-576029346.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, i